import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { fileURLToPath, URL } from 'node:url'

// ---------------------------------------------------------------------------
// Prerender route list — exported so the prerender script can import it.
// Every URL listed here gets rendered to a real static HTML file at build
// time, so Google and other crawlers receive full content (not a blank shell).
// Add new routes here whenever new pages are created.
// ---------------------------------------------------------------------------
export const prerenderRoutes = [
  '/',
  '/projects',
  '/service-areas',
  '/contact',
  '/blog',
  // Services
  '/custom-joinery',
  '/kitchens',
  '/wardrobes',
  '/laundry',
  '/renovations',
  '/bathrooms',
  '/shelving-storage',
  // Projects
  '/projects/beaumont-hills-home-renovation',
  '/projects/carlton-kitchen-renovation',
  '/projects/castle-hill-kitchen-laundry-renovation',
  '/projects/cremorne-project',
  '/projects/croydon-apartment-renovation',
  '/projects/darlinghurst',
  '/projects/epping',
  '/projects/glebe-kitchen-renovation',
  '/projects/harrington-park-home-renovation',
  '/projects/james-lane-moore-park',
  '/projects/lurnea-kitchen-renovation',
  '/projects/monterey-kitchen-butlers-wardrobe',
  '/projects/mosman-custom-wardrobes',
  '/projects/neutral-bay-home-renovation',
  '/projects/pemulwuy-kitchen-office-fitout',
  '/projects/rosemeadow-kitchen-renovation',
  '/projects/vaucluse-kitchen-remodel',
  '/projects/willoughby',
  // Blog posts
  '/blog/kitchen-renovation-cost-sydney',
  '/blog/custom-joinery-vs-flat-pack-sydney',
  // Service areas
  '/service-areas/annandale',
  '/service-areas/balmain',
  '/service-areas/bankstown',
  '/service-areas/beaumont-hills',
  '/service-areas/bellevue-hill',
  '/service-areas/bondi-junction',
  '/service-areas/bondi',
  '/service-areas/bronte',
  '/service-areas/campbelltown',
  '/service-areas/carlton',
  '/service-areas/castle-hill',
  '/service-areas/chatswood',
  '/service-areas/clovelly',
  '/service-areas/coogee',
  '/service-areas/cremorne',
  '/service-areas/crows-nest',
  '/service-areas/croydon',
  '/service-areas/darlinghurst',
  '/service-areas/double-bay',
  '/service-areas/epping',
  '/service-areas/five-dock',
  '/service-areas/glebe',
  '/service-areas/harrington-park',
  '/service-areas/hunters-hill',
  '/service-areas/kensington',
  '/service-areas/kingsford',
  '/service-areas/lane-cove',
  '/service-areas/leichhardt',
  '/service-areas/liverpool',
  '/service-areas/lurnea',
  '/service-areas/manly',
  '/service-areas/maroubra',
  '/service-areas/marrickville',
  '/service-areas/monterey',
  '/service-areas/moore-park',
  '/service-areas/mosman',
  '/service-areas/neutral-bay',
  '/service-areas/newtown',
  '/service-areas/paddington',
  '/service-areas/parramatta',
  '/service-areas/pemulwuy',
  '/service-areas/pyrmont',
  '/service-areas/randwick',
  '/service-areas/redfern',
  '/service-areas/rose-bay',
  '/service-areas/rosemeadow',
  '/service-areas/rozelle',
  '/service-areas/surry-hills',
  '/service-areas/vaucluse',
  '/service-areas/wahroonga',
  '/service-areas/willoughby',
  '/service-areas/woollahra',
  '/service-areas/zetland',
]

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
})
